[
  { name: 'Buck McKeon', title: 'Co-Chair', leader: true, state: State.find_by_abbreviation('CA'), district: '25', url: 'http://mckeon.house.gov/' },
  { name: 'Henry Cuellar', title: 'Co-Chair', leader: true, state: State.find_by_abbreviation('TX'), district: '28', url: 'http://cuellar.house.gov/' },
  { name: 'Todd Akin', url: 'http://akin.house.gov', state: State.find_by_abbreviation('MO'), district: '2' },
  { name: 'Steve Austria', url: 'http://austria.house.gov', state: State.find_by_abbreviation('OH'), district: '7' },
  { name: 'Roscoe G. Bartlett', url: 'http://bartlett.house.gov/', state: State.find_by_abbreviation('MD'), district: '6' },
  { name: 'Rick Berg', url: 'http://berg.house.gov', state: State.find_by_abbreviation('ND'), district: 'At Large' },
  { name: 'Shelley Berkley', url: 'http://berkley.house.gov', state: State.find_by_abbreviation('NV'), district: '01' },
  { name: 'Brian Bilbray', url: 'http://bilbray.house.gov', state: State.find_by_abbreviation('CA'), district: '50' },
  { name: 'Rob Bishop', url: 'http://robbishop.house.gov/', state: State.find_by_abbreviation('UT'), district: '1' },
  { name: 'Dan Boren', url: 'http://boren.house.gov', state: State.find_by_abbreviation('OK'), district: '02' },
  { name: 'Anne Marie Buerkle', url: 'http://buerkle.house.gov', state: State.find_by_abbreviation('NY'), district: '25' },
  { name: 'Robert Brady', url: 'http://www.brady.house.gov', state: State.find_by_abbreviation('PA'), district: '1' },
  { name: 'Mo Brooks', url: 'http://brooks.house.gov', state: State.find_by_abbreviation('AL'), district: '5' },
  { name: 'Madeleine Bordallo', url: 'http://www.house.gov/bordallo', state: State.find_by_abbreviation('Guam'), district: nil },
  { name: 'Larry Bucshon', url: 'http://bucshon.house.gov', state: State.find_by_abbreviation('IN'), district: '6' },
  { name: 'Ken Calvert', url: 'http://calvert.house.gov', state: State.find_by_abbreviation('CA'), district: '44' },
  { name: 'Tom Cole', url: 'http://cole.house.gov', state: State.find_by_abbreviation('OK'), district: '4' },
  { name: 'Mike Conaway', url: 'http://conaway.house.gov', state: State.find_by_abbreviation('TX'), district: '11' },
  { name: 'Gerald Connolly', url: 'http://connolly.house.gov/', state: State.find_by_abbreviation('VA'), district: '11' },
  { name: 'Joe Courtney', url: 'http://courtney.house.gov', state: State.find_by_abbreviation('CT'), district: '2' },
  { name: 'Ander Crenshaw', url: 'http://crenshaw.house.gov', state: State.find_by_abbreviation('FL'), district: '4' },
  { name: 'Norman Dicks', url: 'http://www.house.gov/dicks', state: State.find_by_abbreviation('WA'), district: '6' },
  { name: 'David Dreier', url: 'http://dreier.house.gov/index.shtml', state: State.find_by_abbreviation('CA'), district: '26' },
  { name: 'Blake Farenthold', url: 'http://farenthold.house.gov/', state: State.find_by_abbreviation('TX'), district: '27' },
  { name: 'Randy J. Forbes', url: 'http://forbes.house.gov', state: State.find_by_abbreviation('VA'), district: '4' },
  { name: 'Trent Franks', url: 'http://www.franks.house.gov/', state: State.find_by_abbreviation('AZ'), district: '2' },
  { name: 'Elton Gallegly', url: 'http://www.house.gov/gallegly/', state: State.find_by_abbreviation('CA'), district: '24' },
  { name: 'Paul Gosar', url: 'http://gosar.house.gov', state: State.find_by_abbreviation('AZ'), district: '1' },
  { name: 'Gene Green', url: 'http://green.house.gov', state: State.find_by_abbreviation('TX'), district: '12' },
  { name: 'Colleen Hanabusa', url: 'http://hanabusa.house.gov', state: State.find_by_abbreviation('HI'), district: '1' },
  { name: 'Richard Hanna', url: 'http://hanna.house.gov', state: State.find_by_abbreviation('NY'), district: '24' },
  { name: 'Andy Harris', url: 'http://harris.house.gov/', state: State.find_by_abbreviation('NY'), district: '24' },
  { name: 'Vicky Hartzler', url: 'http://hartzler.house.gov', state: State.find_by_abbreviation('MO'), district: '4' },
  { name: 'Joe Heck', url: 'http://heck.house.gov', state: State.find_by_abbreviation('NV'), district: '3' },
  { name: 'Maurice Hinchey', url: 'http://hinchey.house.gov', state: State.find_by_abbreviation('NY'), district: '22' },
  { name: 'Duncan Hunter', url: 'http://hunter.house.gov', state: State.find_by_abbreviation('CA'), district: '52' },
  { name: 'Darrell Issa', url: 'http://issa.house.gov', state: State.find_by_abbreviation('CA'), district: '49' },
  { name: 'Lynn Jenkins', url: 'http://jenkins.house.gov', state: State.find_by_abbreviation('KS'), district: '2' },
  { name: 'William Keating', url: 'http://keating.house.gov/', state: State.find_by_abbreviation('MA'), district: '10' },
  { name: 'Doug Lamborn', url: 'http://lamborn.house.gov', state: State.find_by_abbreviation('CO'), district: '5' },
  { name: 'Jerry Lewis', url: 'http://jerrylewis.house.gov', state: State.find_by_abbreviation('CA'), district: '41' },
  { name: 'Frank LoBiondo', url: 'http://www.house.gov/lobiondo/', state: State.find_by_abbreviation('NJ'), district: '2' },
  { name: 'Frank Lucas', url: 'http://lucas.house.gov/', state: State.find_by_abbreviation('OK'), district: '03' },
  { name: 'Kevin McCarthy', url: 'http://kevinmccarthy.house.gov/', state: State.find_by_abbreviation('CA'), district: '22' },
  { name: 'Michael T. McCaul', url: 'http://mccaul.house.gov', state: State.find_by_abbreviation('TX'), district: '10' },
  { name: 'Candice Miller', url: 'http://candicemiller.house.gov', state: State.find_by_abbreviation('MI'), district: '10' },
  { name: 'Pete Olson', url: 'http://olson.house.gov', state: State.find_by_abbreviation('TX'), district: '22' },
  { name: 'Steven Palazzo', url: 'http://palazzo.house.gov', state: State.find_by_abbreviation('MS'), district: '04' },
  { name: 'Steve Pearce', url: 'http://pearce.house.gov/', state: State.find_by_abbreviation('NM'), district: '02' },
  { name: 'Mike Pompeo', url: 'http://pompeo.house.gov', state: State.find_by_abbreviation('KS'), district: '4' },
  { name: 'Silvestre Reyes', url: 'http://reyes.house.gov', state: State.find_by_abbreviation('TX'), district: '16' },
  { name: 'Dana Rohrabacher', url: 'http://rohrabacher.house.gov', state: State.find_by_abbreviation('CA'), district: '46' },
  { name: 'Thomas Rooney', url: 'http://rooney.house.gov', state: State.find_by_abbreviation('FL'), district: '16' },
  { name: 'Loretta Sanchez', url: 'http://lorettasanchez.house.gov', state: State.find_by_abbreviation('CA'), district: '47' },
  { name: 'Rep Mike Simpson', url: 'http://simpson.house.gov/', state: State.find_by_abbreviation('ID'), district: '2' },
  { name: 'Edolphus "Ed" Towns', url: 'http://towns.house.gov', state: State.find_by_abbreviation('NY'), district: '10' },
  { name: 'Michael R. Turner', url: 'http://turner.house.gov', state: State.find_by_abbreviation('OH'), district: '3' },
  { name: 'Joe Wilson', url: 'http://joewilson.house.gov', state: State.find_by_abbreviation('SC'), district: '2' },
  { name: 'Robert J. Wittman', url: 'http://wittman.house.gov', state: State.find_by_abbreviation('VA'), district: '1' },
  { name: 'Don Young', url: 'http://donyoung.house.gov', state: State.find_by_abbreviation('AK'), district: 'At Large' }
].each { |representative_attributes| Representative.find_or_create_by_name(representative_attributes) }
